### ISSUE TITLE
queue.js broken

### ISSUE THREAD

**Issue by hyperx47** [BlueFox-Development/Discord-Bot-Example#8]
(node:12908) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'splitEmbedDescription' of undefined

**Comment by FlaringPhoenix** [comment]
I will get this fixed today. Thanks for reporting it

**Comment by TheGamer456YT** [comment]
Should work with the latest commit (144137b)[https://github.com/BlueFox-Development/Discord-Bot-Example/commit/144137beab448505c34b0f43d45d0d2135dee5a3]

**Comment by TheGamer456YT** [comment]
I accidentally locked it... Sorry!

**Comment by hyperx47** [comment]
No its your bot you can do whatever you want lol

**Comment by hyperx47** [comment]
And thanks to you im learning alot from this

**Comment by TheGamer456YT** [comment]
My pleasure! I'm always here to help! Have you deployed it again? And did it work? If it didn't, please report it in this issue again! And thanks for the report!

**Comment by hyperx47** [comment]
yep i think everything is working fine

**Comment by TheGamer456YT** [comment]
Epic! Have a good day!

**Comment by hyperx47** [comment]
Uh after 10min running properly it just pop up a new error

**Comment by hyperx47** [comment]
oh nvm i fixed it myself lol

**Comment by TheGamer456YT** [comment]
lol

**Comment by hyperx47** [comment]
xd
